---
- name: Verify
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: "Verify tasks"
      when: not (ansible_os_family in ['RedHat', 'Rocky', 'OracleLinux'] and ansible_distribution_major_version == '8')
      block:
        - name: Collect packages as facts
          ansible.builtin.package_facts:

        - name: Check package installed
          ansible.builtin.assert:
            that:
              - "'chrony' in ansible_facts.packages"

        - name: Collect services as facts
          ansible.builtin.service_facts:

        - name: Check service is running
          ansible.builtin.assert:
            that:
              - "ansible_facts.services['chrony.service'].state == 'running'"
